# https://github.com/johnnymetz/notifier-app/network/updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  #    - package-ecosystem: npm
  #      directory: /frontend
  #      open-pull-requests-limit: 20
  #      schedule:
  #        interval: monthly
  #      assignees:
  #        - johnnymetz
  #  - package-ecosystem: pip
  #    directory: /
  #    schedule:
  #      interval: monthly
  #    open-pull-requests-limit: 20
  #    assignees:
  #      - johnnymetz
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
    assignees:
      - johnnymetz
