# https://github.com/johnnymetz/notifier-app/network/updates

version: 2
updates:
  - package-ecosystem: pip-compile
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
    assignees:
      - johnnymetz
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
    assignees:
      - johnnymetz
