default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        args: ['--config=api/pyproject.toml']
  - repo: https://github.com/pycqa/isort
    rev: 5.10.0
    hooks:
      - id: isort
        args: ['--settings-file=api/pyproject.toml']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--config=api/.flake8']
        additional_dependencies:
          [
            'flake8-broken-line',
            'flake8-bugbear',
            'flake8-builtins',
            'flake8-comprehensions',
            'flake8-print',
            'flake8-pytest-style',
            'flake8-return',
            'flake8-spellcheck',
            'flake8-tuple',
            'pep8-naming',
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        args: ['--config-file=api/mypy.ini']
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.0'
    hooks:
      - id: bandit
        args: ['--skip=B101', '--exclude=tests']
  # docker pull hadolint/hadolint (to update hadolint image)
  - repo: https://github.com/hadolint/hadolint
    # https://github.com/hadolint/hadolint/issues/697
    rev: 'v2.8.0'
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: 'v2.0.1'
    hooks:
      - id: docker-compose-check
  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: 'v0.11.0'
  #   hooks:
  #     - id: markdownlint
  - repo: local
    hooks:
      - id: pre-commit-django-migrations
        name: Check django migrations
        entry: docker compose run api ./manage.py makemigrations --dry-run --check
        language: system
        types: [python]
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast # validate python
      - id: check-merge-conflict # validate no merge conflict strings
      - id: check-json # validate json
      - id: check-yaml # validate yaml
      - id: check-docstring-first # validate no code is placed before docstring
      - id: check-added-large-files # reject giant files (default=500kB)
        args: ['--maxkb=1500'] # bump from 500 kb default for images
      - id: fix-byte-order-marker # removes UTF-8 byte order marker
      - id: check-symlinks # check for broken symlinks
      - id: debug-statements # validate no breakpoint() calls in python source
      - id: detect-private-key # keep those keys safe
      - id: end-of-file-fixer # add newline at end of files
      - id: trailing-whitespace # trim trailing whitespace
        # exclude: \.snap # ignore snapshots
