ci:
  autofix_prs: false
  skip:
    - docker-compose-check
    - hadolint-docker
    - pre-commit-django-migrations

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.16.0'
    hooks:
      - id: django-upgrade
        args: [--target-version, '5.0']
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args: ['--py311-plus']
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
            # https://github.com/wemake-services/flake8-broken-line/issues/281
            # 'flake8-broken-line',
            'flake8-bugbear',
            'flake8-builtins',
            'flake8-comprehensions',
            'flake8-print',
            'flake8-pytest-style',
            'flake8-return',
            'flake8-spellcheck',
            'flake8-tuple',
            'pep8-naming',
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: ['types-requests']
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.7'
    hooks:
      - id: bandit
        args: ['--skip=B101', '--exclude=tests']
  # docker pull hadolint/hadolint (to update hadolint image)
  - repo: https://github.com/hadolint/hadolint
    # https://github.com/hadolint/hadolint/issues/697
    rev: 'v2.12.1-beta'
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: 'v3.0.1'
    hooks:
      - id: docker-compose-check
  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: 'v0.11.0'
  #   hooks:
  #     - id: markdownlint
  - repo: local
    hooks:
      - id: pre-commit-django-migrations
        name: Check django migrations
        entry: docker compose run -T api ./manage.py makemigrations --dry-run --check
        language: system
        types: [python]
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast # validate python
      - id: check-merge-conflict # validate no merge conflict strings
      - id: check-json # validate json
      - id: check-yaml # validate yaml
      - id: check-docstring-first # validate no code is placed before docstring
      - id: check-added-large-files # reject giant files (default=500kB)
        args: ['--maxkb=1500'] # bump from 500 kb default for images
      - id: fix-byte-order-marker # removes UTF-8 byte order marker
      - id: check-symlinks # check for broken symlinks
      - id: debug-statements # validate no breakpoint() calls in python source
      - id: detect-private-key # keep those keys safe
      - id: end-of-file-fixer # add newline at end of files
      - id: trailing-whitespace # trim trailing whitespace
        # exclude: \.snap # ignore snapshots
