default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.0'
    hooks:
      - id: bandit
        args: ['--skip=B101', '--exclude=tests']
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: ''
    hooks:
      - id: docker-compose-check
      - id: hadolint
  - repo: https://github.com/markdownlint/markdownlint
    rev: 'v0.11.0'
    hooks:
      - id: markdownlint
  - repo: local
    hooks:
      - id: pre-commit-django-migrations
        name: Check django migrations
        entry: docker-compose exec -T api ./manage.py makemigrations --dry-run --check
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast # validate python
      - id: check-merge-conflict # validate no merge conflict strings
      - id: check-json # validate json
      - id: check-yaml # validate yaml
      - id: check-docstring-first # validate no code is placed before docstring
      - id: check-added-large-files # reject giant files (default=500kB)
        args: ['--maxkb=1500'] # bump from 500 kb default for images
      - id: check-byte-order-marker # reject files which have a UTF-8 byte-order marker
      - id: check-symlinks # check for broken symlinks
      - id: debug-statements # validate no breakpoint() calls in python source
      - id: detect-private-key # keep those keys safe
      - id: end-of-file-fixer # add newline at end of files
      - id: trailing-whitespace # trim trailing whitespace
        exclude: \.snap # ignore snapshots
