version: '3'
services:
  frontend-cypress:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_HOST=http://api:8000/api/
    depends_on:
      - api

  cypress:
    image: cypress/included:3.3.2
    ipc: host # https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772
    working_dir: /app
    volumes:
      - ./frontend/cypress:/app/cypress
      - ./frontend/cypress-docker.json:/app/cypress.json
      - ./frontend/cypress.env.json:/app/cypress.env.json
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    # environment:
    #   - DISPLAY=192.168.1.79:0
    # entrypoint: cypress open --project .
    depends_on:
      - frontend-cypress
