version: '3'
services:
  api:
    command: bash -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    # disable logging to reduce noise;
    # not working: https://github.com/docker/compose/issues/8578
    logging:
      driver: none

  frontend-dev:
    environment:
      - NEXT_PUBLIC_API_HOST=http://api:8000/api/

  cypress:
    # https://hub.docker.com/r/cypress/included/tags
    image: cypress/included:6.4.0
    ipc: host # https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772
    working_dir: /app
    volumes:
      - ./frontend/cypress:/app/cypress
      - ./frontend/cypress-docker.json:/app/cypress.json
      - ./frontend/cypress.env.json:/app/cypress.env.json
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    # environment:
    #   - DISPLAY=192.168.1.79:0
    # entrypoint: cypress open --project .
    depends_on:
      - frontend-dev
