services:
  db:
    image: postgres:13
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=${DATABASE_NAME}

  api:
    build: .
    image: notifier-app_api
    command: newrelic-admin run-program ./manage.py runserver 0.0.0.0:8000
    # command: gunicorn api.wsgi:application --bind=0.0.0.0:8000 --config python:api.gunicorn_conf --reload
    ports:
      - '8000:8000'
    tty: true # enables colorized logs with rich package
    volumes:
      - .:/app
      - ./ipython_config.py:/root/.ipython/profile_me/ipython_config.py
      - /app/frontend
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings
      - DB_HOST=db
    depends_on:
      - db

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    # command: tail -f /dev/null  # keep container running for debugging
    ports:
      - '3001:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_HOST=http://0.0.0.0:8000/
    depends_on:
      - api

  frontend-prd:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_HOST=http://0.0.0.0:8000/
    ports:
      - '81:80'
    depends_on:
      - api

volumes:
  postgres_data:
