version: '3'
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    ports:
      - '5672:5672'

  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings
      - CELERY_BROKER_URL=amqp://rabbit/
    depends_on:
      - rabbit

  celeryworker:
    build: ./api
    command: watchmedo auto-restart -d ./ -p '*.py' -R -- celery worker -A api -l info
    volumes:
      - ./api:/app
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings
      - CELERY_BROKER_URL=amqp://rabbit/
    depends_on:
      - rabbit

  celerybeat:
    build: ./api
    command: watchmedo auto-restart -d ./ -p '*.py' -R -- celery beat -A api -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./api:/app
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings
      - CELERY_BROKER_URL=amqp://rabbit/
    depends_on:
      - rabbit
