version: '3'
services:
  db:
    image: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres

  # rabbit:
  #   hostname: rabbit
  #   image: rabbitmq:latest
  #   ports:
  #     - '5672:5672'

  # flower:
  #   image: mher/flower:latest
  #   command: flower --port=5555 --broker=amqp://rabbit/
  #   ports:
  #     - '5555:5555'
  #   depends_on:
  #     - rabbit

  api:
    build: ./api
    image: notifier-app_api
    command: ./manage.py runserver 0.0.0.0:8000
    # command: bash -c "
    #   ./manage.py migrate &&
    #   ./manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings.local
      - DB_HOST=db
      - CELERY_BROKER_URL=amqp://rabbit/
      - QA_USER_EMAIL
    depends_on:
      - db
      # - rabbit

  # celeryworker:
  #   image: notifier-app_api
  #   command: watchmedo auto-restart -d ./ -p '*.py' -R -- celery worker -A api -l info
  #   volumes:
  #     - ./api:/app
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=api.settings.local
  #     - DB_HOST=db
  #     - CELERY_BROKER_URL=amqp://rabbit/
  #   depends_on:
  #     - api

  # celerybeat:
  #   image: notifier-app_api
  #   command: watchmedo auto-restart -d ./ -p '*.py' -R -- celery beat -A api -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #   volumes:
  #     - ./api:/app
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=api.settings.local
  #     - DB_HOST=db
  #     - CELERY_BROKER_URL=amqp://rabbit/
  #   depends_on:
  #     - api

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - api

volumes:
  postgres_data:
