version: '3'
services:
  db:
    image: postgres:13
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notifier

  api:
    build: ./api
    image: notifier-app_api
    command: ./manage.py runserver 0.0.0.0:8000
    # command: gunicorn api.wsgi:application --bind=0.0.0.0:8000 --timeout=20 --reload
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app
      - ./api/ipython_config.py:/root/.ipython/profile_me/ipython_config.py
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings.local
      - DB_HOST=db
      - DB_NAME=notifier
      - QA_USER_EMAIL1
      - QA_USER_EMAIL2
      - QA_USER_PASSWORD
    depends_on:
      - db

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3000'
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_HOST=http://0.0.0.0:8000/api/
    depends_on:
      - api

volumes:
  postgres_data:
