# # Doesn't currently work
# version: '3'
# services:
#   api:
#     command: bash -c "
#       ./manage.py migrate &&
#       ./manage.py collectstatic --noinput &&
#       gunicorn api.wsgi:application --bind=0.0.0.0:8000 --reload"
#     environment:
#       - DJANGO_SETTINGS_MODULE=api.settings.production
#       - SECRET_KEY
#       - ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#       - ADMIN_URL=admin
#       - SENDGRID_USERNAME
#       - SENDGRID_PASSWORD

#   celeryworker:
#     environment:
#       - DJANGO_SETTINGS_MODULE=api.settings.production
#       - SECRET_KEY
#       - ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#       - ADMIN_URL=admin
#       - SENDGRID_USERNAME
#       - SENDGRID_PASSWORD

#   celerybeat:
#     environment:
#       - DJANGO_SETTINGS_MODULE=api.settings.production
#       - SECRET_KEY
#       - ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#       - ADMIN_URL=admin
#       - SENDGRID_USERNAME
#       - SENDGRID_PASSWORD
