version: '3'
services:
  api:
    command: gunicorn --bind=0.0.0.0:8000 --log-level=debug --reload api.wsgi:application
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings.production
      - SECRET_KEY
      - ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD

  celeryworker:
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings.production
      - SECRET_KEY
      - ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD

  celerybeat:
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings.production
      - SECRET_KEY
      - ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
