[tool.black]
target-version = ["py311"]
include = '\.pyi?$'
# change to extend-exclude on new release
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | venv
)/
'''
# files in this dir are ignored by pre-commit
force-exclude = '''
/(
  migrations
)\
'''

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_first_party = ["api", "users", "notifier", "play"]
known_django = "django"
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
remove_redundant_aliases = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "api.settings"
django_debug_mode = true
addopts= [
  "--verbose",
  "-ra",
  "--disable-socket",
  "--doctest-modules",
  "--instafail",
  "--cov=.",
  "--cov-report=term-missing",
  # ignore files that break doctest
  "--ignore=ipython_config.py",
  "--ignore=scripts/",
  "--ignore-glob=api/settings/*",
]
markers = [
  "skip_nplusone: mark test to not raise an error when an n+1 query is detected",
]
filterwarnings = [
    # Causes pytest to raise an exception if any warnings are emitted,
    # besides those explicitly ignored below.
    "error",
    # Ignore deprecation warnings from third-party packages
    "ignore:pkg_resources is deprecated as an API:DeprecationWarning",
    "ignore:Deprecated call to `pkg_resources.declare_namespace\\(('zope')\\)`:DeprecationWarning",
    "ignore:'cgi' is deprecated and slated for removal in Python 3.13:DeprecationWarning",
    "ignore:The django.utils.timezone.utc alias is deprecated:django.utils.deprecation.RemovedInDjango50Warning:rest_framework_simplejwt",
]
# timeout for a single test; comment out when debugging
timeout = 20

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
show_error_codes = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = "*.migrations.*"
ignore_errors = true

[tool.coverage.run]
omit = [
  "manage.py",
  "*wsgi.py",
  "*asgi.py",
  "*swagger.py",
  "*/settings/*",
  "*/tests*",
  "ipython_config.py",
]
branch = true
