# Generated by Django 3.1.1 on 2020-11-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_increase_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_subscribed",
            field=models.BooleanField(default=True),
        ),
    ]
