# Generated by Django 3.1.3 on 2020-12-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Birthday", "Birthday"),
                            ("Holiday", "Holiday"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("annual_date", models.DateField()),
            ],
            options={
                "ordering": ["annual_date__month", "annual_date__day"],
            },
        ),
    ]
