[tool.black]
line-length = 88
target-version = ['py38']  # update to py39 on new release
include = '\.pyi?$'
# change to extend-exclude on new release
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | venv
  | migrations
)/
'''

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_first_party = ["api", "users", "notifier"]
known_django = "django"
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
remove_redundant_aliases = true
