[tool.black]
target-version = ["py38"]  # update to py39 on new release
include = '\.pyi?$'
# change to extend-exclude on new release
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | venv
)/
'''
# files in this dir are ignored by pre-commit
force-exclude = '''
/(
  migrations
)\
'''

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_first_party = ["api", "users", "notifier"]
known_django = "django"
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
remove_redundant_aliases = true

[tool.pytest.ini_options]
django_debug_mode = true
addopts= [
  "--ds=api.settings.test",
  "--verbose",
  "-ra",
  "--doctest-modules",
  "--instafail",
  "--cov=.",
  # "--cov-config .coveragerc",
  "--cov-report=term-missing",
  # ignore files that break doctest
  "--ignore=ipython_config.py",
  "--ignore=scripts/",
  "--ignore-glob=api/settings/*",
]
markers = [
  "skip_nplusone: mark test to not raise an error when an n+1 query is detected",
]
# timeout for a single test; comment out when debugging
timeout = 20

[tool.coverage.run]
omit = [
  "manage.py",
  "*wsgi.py",
  "*asgi.py",
  "*swagger.py",
  "*/settings/*",
  "*/tests*",
  "ipython_config.py",
]
