name: Build and Test on Main
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: 'DONOTUSEINPRODUCTION'
    steps:
      - uses: actions/checkout@v4
      - name: Parse Python version
        run: sed s/python-// runtime.txt | head > .python-version
      - uses: actions/setup-python@v4
        with:
          cache: pip
      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Pytest
        run: pytest --durations 10
#  cypress-run:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Run Cypress tests
#        # # https://github.com/cypress-io/github-action#explicit-version
#        uses: cypress-io/github-action@v5
#        with:
#          working-directory: frontend
#          browser: chrome
