name: Build and Test on Main
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Login to Dockerhub
      #   run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build api image
        run: docker build api --tag notifier-api
      - name: Run api tests
        run: docker run notifier-api pytest
